---
title: "Alex's Trees"
author: "Alex Carriero"
date: '2022-11-01'
output: html_document
---
# Prep
## Libraries
```{r, warning = F, message = F}
library(readr)
library(tidyverse)
library(psych)
library(MASS)
library(pROC)
library(randomForest)
library(xgboost)
library(rpart)
library(rpart.plot)
library(jtools)
library(class)
library(ISLR)
library(Matrix)

# NEW 
library(caret)
library(devtools)
library(ggspectra)
library(CalibrationCurves)
source_url("https://github.com/pablo14/shap-values/blob/master/shap.R?raw=TRUE")
```

## Tidy the data

```{r}
# import data
data<- read.csv("mushrooms.csv")
```

```{r}
# tidy data -- merge redundant categories 
mushrooms <- data %>% 
    mutate(across(where(is.character), as_factor))%>%
    dplyr::select(-veil.type, -stalk.root)%>%     
    mutate(cap.shape = cap.shape %>% 
             fct_recode("bell"    = "b",
                        "conical" = "c",
                        "convex"  = "x",
                        "flat"    = "f", 
                        "knobbed" = "k",
                        "sunken"  = "s"),
           cap.surface = cap.surface %>% 
             fct_recode("fibrous" = "f",
                        "grooves" = "g",
                        "scaly"   = "y",
                        "smooth"  = "s"), 
           bruises = bruises %>% 
             fct_recode("true"       = "t",
                        "false"      = "f"), 
           odor = odor %>%
             fct_recode("almond"     = "a",
                        "anise"      = "l",
                        "creosote"   = "c",
                        "fishy"      = "y",
                        "foul"       = "f",
                        "musty"      = "m",
                        "none"       = "n",
                        "pungent"    = "p",
                        "spicy"      = "s"),
           cap.color = cap.color %>%                 
             fct_recode("brown"      = "n",
                        "brown"      = "b",
                        "brown"      = "c", 
                        "pink"       = "u",                      
                        "pink"       = "e", 
                        "pink"       = "p", 
                        "gray"       = "g",
                        "green"      = "r", 
                        "white"      = "w",
                        "yellow"     = "y"),
           gill.attachment = gill.attachment %>% 
             fct_recode("attached"   = "a",
                        "free"       = "f"), 
           gill.spacing = gill.spacing %>% 
             fct_recode("close"      = "c",
                        "crowded"    = "w"),
           gill.size = gill.size %>% 
             fct_recode("broad"      = "b",
                        "narrow"     = "n"), 
           gill.color = gill.color %>% 
             fct_recode("black"      ="k",
                        "brown"      ="n",
                        "brown"      ="b",
                        "brown"      ="h",
                        "gray"       ="g", 
                        "green"      ="r",
                        "orange"     ="o",
                        "pink"       ="p",
                        "pink"       ="u",
                        "pink"       ="e",
                        "white"      ="w",
                        "yellow"     ="y"),
           stalk.shape = stalk.shape %>% 
             fct_recode("enlarging"  ="e",
                        "tapering"   ="t"), 
           stalk.surface.above.ring = stalk.surface.above.ring %>% 
             fct_recode("fibrous"    ="f",
                        "scaly"      ="y",
                        "silky"      ="k",
                        "smooth"     ="s"), 
          stalk.surface.below.ring = stalk.surface.below.ring %>% 
             fct_recode("fibrous"    ="f",
                        "scaly"      ="y",
                        "silky"      ="k",
                        "smooth"     ="s"), 
          stalk.color.above.ring = stalk.color.above.ring %>% 
            fct_recode("brown"       ="n",
                       "brown"       ="b",
                       "brown"       ="c",
                       "gray"        ="g",
                       "orange"      ="o",
                       "pink"        ="p",
                       "pink"        ="e",
                       "white"       ="w",
                       "yellow"      ="y",), 
          stalk.color.below.ring = stalk.color.below.ring %>% 
            fct_recode("brown"       ="n",
                       "brown"       ="b",
                       "brown"       ="c",
                       "gray"        ="g",
                       "orange"      ="o",
                       "pink"        ="p",
                       "pink"        ="e",
                       "white"       ="w",
                       "yellow"      ="y",), 
          veil.color = veil.color %>%
            fct_recode("brown"       ="n",
                       "orange"      ="o",
                       "white"       ="w",
                       "yellow"      ="y"),
          ring.number = ring.number %>% 
            fct_recode("none"        ="n",
                       "one"         ="o",
                       "two"         ="t"), 
          ring.type = ring.type %>% 
            fct_recode("evanescent"  ="e",
                       "flaring"     ="f",
                       "large"       ="l",
                       "none"        ="n",
                       "pendant"     ="p"),
          spore.print.color = spore.print.color %>% 
            fct_recode("black"   ="k",
                       "brown"   ="n",
                       "brown"   ="b",
                       "brown"   ="h",
                       "green"   ="r",
                       "orange"  ="o",
                       "purple"  ="u",
                       "white"   ="w",
                       "yellow"  ="y"), 
         population = population %>% 
           fct_recode("group"    ="a",
                      "group"    ="c",
                      "group"    ="n",
                      "group"    ="s",
                      "group"    ="v",
                      "solitary" ="y"), 
         habitat = habitat %>% 
           fct_recode("grasses"  ="g",
                      "woods"    ="l",
                      "grasses"  ="m",
                      "urban"    ="p",
                      "urban"    ="u",
                      "waste"    ="w",
                      "woods"    ="d"))
```

## Partition Data
```{r} 
# set seed 
set.seed(191)

# test and train
n = dim(mushrooms)[1]
mushrooms_split <- mushrooms %>% 
                   mutate(split = sample(rep(c("train", "test"), 
                                             times = c(round(.8*n), round(.2*n)))))

mushrooms_train <- mushrooms_split %>% 
                  filter(split == "train") %>%
                  dplyr::select(-split)

mushrooms_test  <- mushrooms_split %>% 
                  filter(split == "test") %>%
                  dplyr::select(-split)
```

```{r}
# beginner 
beginner       <- mushrooms %>% 
                  dplyr::select(class, cap.shape, cap.color, bruises, gill.color, 
                                stalk.shape, ring.number, population, habitat)

beginner_train <- mushrooms_train %>% 
                  dplyr::select(class, cap.shape, cap.color, bruises, gill.color, 
                                stalk.shape, ring.number, population, habitat)

beginner_test  <- mushrooms_test %>% 
                  dplyr::select(class, cap.shape, cap.color, bruises, gill.color, 
                                stalk.shape, ring.number, population, habitat)
                

# advanced 
advanced       <- mushrooms 
advanced_train <- mushrooms_train
advanced_test  <- mushrooms_test
```


# Trees 


## Beginner 
```{r}
df = beginner_train
```

```{r}
# decision tree
dtree <- rpart(class ~ ., data = df)
rpart.plot(dtree)
```

```{r}
# random forest -- caret library 
cvcontrol <- trainControl(method = "repeatedcv",   # what does this do?
                          number = 10,             # seems important
                          allowParallel = TRUE)

rf_train <- train(class ~ .,
                    data = df, 
                    method = 'rf',
                    trControl = cvcontrol,
                    importance = TRUE)

rf_train %>%
    varImp %>%
    plot

rf_train
```

```{r}
## xgboost Gerko way
train_x <- model.matrix(class ~ ., df)[,-1]
train_y <- as.numeric(df$class) - 1
xgboost_train <- xgboost(data  = train_x,
                         label = train_y, 
                         max.depth = 10,
                         eta = 1,
                         nthread = 4,
                         nrounds = 4,
                         objective = "binary:logistic",
                         verbose = 2)



pred <- tibble(class = predict(xgboost_train, newdata = train_x)) %>%
  mutate(class = factor(ifelse(class < 0.5, 1, 2),
                          labels = c("poison", "eat")))

table(pred$class, df$class)
```

```{r, message = F}
# this doesnt work -- why ?
shap_results <- shap.score.rank(xgboost_train,
                                X_train = train_x,
                                shap_approx = F)

var_importance(shap_results)

shap_long <- shap.prep(shap = shap_results,
                       X_train = train_x)

plot.shap.summary(shap_long)
```

```{r}
# Performance metrics
test <- beginner_test

dt_test  <- predict(dtree, newdata = test) %>%         # garbage code 
            as.data.frame()%>%                         # will fix later (sorry)
            dplyr::select(e) %>% 
            mutate(e = ifelse( e < 0.5, "p", "e")) %>%
            as.matrix()%>% 
            as.vector()%>% 
            as.factor()

rf_test  <- predict(rf_train, newdata = test)
xgb_test <- predict(xgboost_train, newdata = model.matrix(class ~ ., test)[,-1]) %>%
  factor(x = ifelse(. < 0.5, 1, 2), levels = c(1,2), labels = c("p", "e"))

list(dt_test,
     rf_test, 
     xgb_test) %>%
  map(~ confusionMatrix(.x, test$class))
```


```{r, message = F, warning = F}
# calibration plots 
dt_prob <- predict(dtree, newdata = test)
xgb_prob<- predict(xgboost_train, newdata = model.matrix(class ~ ., test)[,-1])
rf_prob <- predict(rf_train, newdata = test, type = "prob")

probs <- tibble(
  class = test$class, 
  dt    = dt_prob[,2], 
  rf    = rf_prob[,2],
  xg    = xgb_prob, 
) %>% 
  mutate(class = ifelse(class == "e", 1, 0))

probs %>%
  gather(key = "variable", value = "value", -class) %>% 
  ggplot(aes(x = value, y = class, color = variable)) + 
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = stats::loess, se = FALSE) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  xlab("Estimated Probability") +
  ylab("Observed Proportion") +
  ggtitle("Logistic Regression Calibration Plot Training")
```

```{r, warning = F}
# one at a time 
val.prob.ci.2(probs$dt, probs$class)
```

## Advanced
```{r}
df = advanced_train
```

```{r}
# decision tree
dtree <- rpart(class ~ ., data = df)
rpart.plot(dtree)
```

```{r}
# random forest -- caret library 
cvcontrol <- trainControl(method = "repeatedcv",   # what does this do?
                          number = 10,             # seems important
                          allowParallel = TRUE)

rf_train <- train(class ~ .,
                    data = df, 
                    method = 'rf',
                    trControl = cvcontrol,
                    importance = TRUE)
```

```{r, fig.height = 10, fig.width = 10}
rf_train %>%
    varImp %>%
    plot

rf_train
```

```{r}
## XG boost
train_x <- model.matrix(class ~ ., df)[,-1]
train_y <- as.numeric(df$class) - 1
xgboost_train <- xgboost(data  = train_x,
                         label = train_y, 
                         max.depth = 10,
                         eta = 1,
                         nthread = 4,
                         nrounds = 4,
                         objective = "binary:logistic",
                         verbose = 2)



pred <- tibble(class = predict(xgboost_train, newdata = train_x)) %>%
  mutate(class = factor(ifelse(class < 0.5, 1, 2),
                          labels = c("poison", "eat")))

table(pred$class, df$class)
```

```{r, message = F}
shap_results <- shap.score.rank(xgboost_train,
                                X_train = train_x,
                                shap_approx = F)

var_importance(shap_results)

shap_long <- shap.prep(shap = shap_results,  
                       X_train = train_x)

plot.shap.summary(shap_long)                              # doesnt work!!
```

```{r}
# Performance metrics 

test <- advanced_test

dt_test  <- predict(dtree, newdata = test) %>%         # garbage code 
            as.data.frame()%>%                         # will fix later (sorry)
            dplyr::select(e) %>% 
            mutate(e = ifelse( e < 0.5, "p", "e")) %>%
            as.matrix()%>% 
            as.vector()%>% 
            as.factor()
rf_test  <- predict(rf_train, newdata = test)
xgb_test <- predict(xgboost_train, newdata = model.matrix(class ~ ., test)[,-1]) %>%
  factor(x = ifelse(. < 0.5, 1, 2), levels = c(1,2), labels = c("p", "e"))

list(rf_test, 
     xgb_test) %>%
  map(~ confusionMatrix(.x, test$class))
```

```{r, message = F, warning = F}
# calibration plots 
dt_prob <- predict(dtree, newdata = test)
xgb_prob<- predict(xgboost_train, newdata = model.matrix(class ~ ., test)[,-1])
rf_prob <- predict(rf_train, newdata = test, type = "prob")

probs <- tibble(
  class = test$class, 
  dt    = dt_prob[,2], 
  rf    = rf_prob[,2],
  xg    = xgb_prob, 
) %>% 
  mutate(class = ifelse(class == "e", 1, 0))

probs %>%
  gather(key = "variable", value = "value", -class) %>% 
  ggplot(aes(x = value, y = class, color = variable)) + 
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = stats::loess, se = FALSE) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  xlab("Estimated Probability") +
  ylab("Observed Proportion") +
  ggtitle("Logistic Regression Calibration Plot Training")
```

```{r, warning = F}
# one at a time 
val.prob.ci.2(probs$xg, probs$class) # this is weird
```

# Trying out Calibration Things

```{r}
# try with lr
lr1 <- glm(class~., family = "binomial", data = beginner_train)

p_train <- with(beginner_train, data.frame(class = ifelse(class == "e", 1, 0), 
                                           prob = predict(lr1, type = "response")))

p_test <- with (beginner_test, data.frame(class = ifelse(class == "e", 1, 0), 
                                           prob = predict(lr1, type = "response", 
                                                          newdata = beginner_test)))
```

```{r}
# first way 
require(ggspectra)

ggplot(p_train, aes(prob, class)) +
  geom_point(shape = 21, size = 2) +
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = stats::loess, se = FALSE) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  xlab("Estimated Prob.") +
  ylab("Data w/ Empirical Prob.") +
  ggtitle("Logistic Regression Calibration Plot Training")

ggplot(p_test, aes(prob, class)) +
  geom_point(shape = 21, size = 2) +
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = stats::loess, se = FALSE) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  xlab("Estimated Prob.") +
  ylab("Data w/ Empirical Prob.") +
  ggtitle("Logistic Regression Calibration Plot Test")
```

```{r}
# second way -- this give calibration int, slope and auc (c-statistic = auc)
library(CalibrationCurves)
a <- val.prob.ci.2(p = p_train$prob, y = p_train$class)
c <- val.prob.ci.2(p = p_test$prob,  y = p_test$class)
```

```{r}
# calibration in the large 

# observed proportion
table(beginner_train$class)[2] / (table(beginner_train$class)[1] + table(beginner_train$class)[2])

# average prediction 
mean(p_train$prob)
```


